blog/urls.py
from django.urls import path , reverse_lazy
from django.urls import path , include
from django.urls import path , include
from django.urls import path , reverse_lazy
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog_list/' , views.PostList.as_view(), name = 'blog_list'),
    path('blog_detail/<int:pk_from_url>' , views.PostDetail.as_view(), name = 'blog_detail'),
    path('' , views.PostList.as_view(), name = 'blog_list'),
    path('<int:pk_from_url>/detail' , views.PostDetail.as_view(), name = 'blog_detail'),
    path('blog_create/' ,
        views.PostCreate.as_view(success_url = reverse_lazy('blog:blog_list')), name = 'blog_create'),
    path('cat_create/' ,
        views.CatCreate.as_view(success_url = reverse_lazy('blog:blog_create')), name = 'cat_create'),
    path('<int:pk>/delete', 
        views.PostDelete.as_view(success_url=reverse_lazy('blog:blog_list')), name='blog_delete'),
    path('<int:pk>/update', 
        views.PostUpdate.as_view(success_url=reverse_lazy('blog:blog_list')), name='blog_Update'),
    path('blog_list/' , views.PostList.as_view(), name = 'blog_list'),
    path('blog_detail/<int:pk_from_url>' , views.PostDetail.as_view(), name = 'blog_detail'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.AdminSite.site_header = 'Blog Site'

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/" , include('blog.urls')),
    path("" , include('users.urls')),
]

urlpatterns += staticfiles_urlpatterns()

users/urls.py
from django.urls import path , include
from . import views

app_name = 'users'

urlpatterns = [
    path('register/' , views.register , name = 'register'),
    path('logout/' , views.logout , name = 'logout'),
    path('' , views.login , name = 'login'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=150)
    
    def __str__(self) -> str:
        return self.name

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    categories = models.CharField(max_length=200 , default='undefined')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.title

users/models.py
from django.db import models

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost, Category
from django.views import View
from .models import BlogPost , Category
from django.views import View
from .form import BlogCreateView
from django.views.generic import DeleteView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

class PostList(View):
    def get(self , request):
        data = BlogPost.objects.all()
        return render(request , 'blog/blog_list.html' , {'posts':data})

class PostDetail(View):
    def get(self , request , pk_from_url):
        data = BlogPost.objects.get(pk = pk_from_url)
        return render(request , 'blog/blog_detail.html' , {'posts':data} )
    
class PostCreate(LoginRequiredMixin , CreateView):
    model = BlogPost
    form_class = BlogCreateView
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
class CatCreate(LoginRequiredMixin , CreateView):
    model = Category
    fields = '__all__'
    
class PostUpdate(LoginRequiredMixin , UpdateView):
    model = BlogPost
    form_class = BlogCreateView
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        
        return super().form_valid(form)

class PostDelete(DeleteView):
    model = BlogPost

users/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import login as auth_login , logout
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from .form import UserCreateForm

def register(request):
    if request.method == 'POST':
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save() 
            auth_login(request , user) 
            return redirect('blog:blog_list')
    else:
        form = UserCreateForm() 
    return render(request , 'users/register.html' , {'form' : form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            auth_login(request , form.get_user())
            return redirect('blog:blog_list')
    else:
        form = AuthenticationForm(request)
    return render(request , 'users/login.html' , {'form':form})

def logout(request):
    logout(request)

blog/templates/blog/blog_detail.html
{% extends 'blog_project/base.html' %}

{% block content %}

<h2>Blog Detail</h2>

<p>{{ posts.author }} </p>
<h2>{{posts.title}}</h2>
<p>{{ posts.author }} </p>
<p>{{ posts.content }}</p>

<p>
    <a href="{% url 'blog:blog_list' %}">Go back</a>
</p>

{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'blog_project/base.html' %}

{% block content %}

<h2>Blog List</h2>
{% if posts %}
<ul>
    {% for post in posts %}
        <li>
            <a href="{% url 'blog:blog_detail' post.id %}">
                <h3>{{ post.title }}</h3>
            </a>
            <span>{{ post.created_at }}</span>
        </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no posts.</p>
{% endif %}

{% endblock content %}

blog/templates/blog/blogpost_confirm_delete.html
{% extends "blog_project/base.html" %}
{% block content %}
<h1>Delete Article</h1>

<p>Are you sure you want to delete the article: {{ article }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'blog_project/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class='login-container'>
        <h2 class='login-heading'> Create New Post </h2>
        <form class='login-form' method='post'>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group pb-3">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                </div>
            {% endfor %}
            {% comment %} {{ form.new_categories.label_tag }} {{ form.new_categories }}
            {{ form.new_tags.label_tag }} {{ form.new_tags }} {% endcomment %}
            <div class='form-group'>
                <a href="{% url 'blog:cat_create' %}">Add Another Category</a>
                <button type = 'submit'>Post</button>
                <a href="{% url 'blog:blog_list' %}">Go Back</a>
            </div>
        </form>
    </div>
    
{% endblock%}

blog/templates/blog/category_form.html
{% extends 'blog_project/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class='login-container'>
        <h2 class='login-heading'> Add New Category </h2>
        <form class='login-form' method='post'>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group pb-3">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                </div>
            {% endfor %}
            {% comment %} {{ form.new_categories.label_tag }} {{ form.new_categories }}
            {{ form.new_tags.label_tag }} {{ form.new_tags }} {% endcomment %}
            <div class='form-group'>
                <button type = 'submit'>Add</button>
                <a href="{% url 'blog:blog_create' %}">Go Back</a>
            </div>
        </form>
    </div>
    
{% endblock%}

templates/blog_project/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name = 'viewport' , content = 'width=device-width , initial-scale=1.0'>
        <link rel='stylesheet' type='text/css' href='{% static "assets\style.css" %}'>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <title>Blog Site</title>
    </head>
    <body>
        <header>
            <a hred='#' class = 'bl-name'>BLOG</a>
            <nav>
                <ul class='nav_settings'>
                    <li><a href='#'>Home</a></li>
                    <li><a href='#'>News</a></li>
                    <li><a href='#'>Profile</a></li>
                </ul>
            </nav>
            <form>
                <input class='ctx' type='search' placeholder='Search'/>
            </form>
        </header>

        <div class='main-container'>
            {% block content %}
            {% endblock %}
        </div>


        <footer>

        </footer>
    </body>
</html>

users/templates/users/login.html
{% extends 'blog_project/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class='login-container'>
        <h2 class='login-heading'> Login </h2>
        <form class='login-form' method='post'>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group pb-3">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                </div>
            {% endfor %}
            <div class='form-group'>
                <button type = 'submit'>Login</button>
                <p style='margin:8px;text-align:center'> 
                    Don't have Account! 
                    <span>
                        <a href="{% url 'users:register' %}">SignUp</a>
                    </span> 
                </p>
            </div>
        </form>
    </div>
    
{% endblock%}

users/templates/users/register.html
{% extends 'blog_project/base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class='login-container'>
        <h2 class='login-heading'> SignUp </h2>
        <form class='login-form' method='post'>
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-group pb-3">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                        {% for error in field.errors %}
                        <span class="help-block">{{ error }}</span>
                        {% endfor %}
                </div>
            {% endfor %}
            <div class='form-group'>
                <button type = 'submit'>SignUp</button>
                <p style='margin:8px;text-align:center'> 
                    Already have an Account! 
                    <span>
                        <a href="{% url 'users:login' %}">Login</a>
                    </span> 
                </p>
            </div>
        </form>
    </div>
    
{% endblock%}